### PR TITLE
Update linter.py

### PR DESCRIPTION
**Pull request by demanuel**
This change will support the following error messages:

* `syntax error at test.pl line 4, near "asdasdasd
	print"
test.pl had compilation errors.`

This is caused by a missing `;` in the code

* `Bareword "asdasdasd" not allowed while "strict subs" in use at bin/test.pl line 31.
bin/test.pl had compilation errors.`

caused by using strict mode;

Also has the side efect of simplification of the regexp

### CODE REVIEW

**Comment by CudaText-addons** [comment]
Active repo is here https://github.com/CudaText-addons/cuda_lint_perl
so pls post this PullReq there?

**Comment by CudaText-addons** [comment]
merged to my fork https://github.com/CudaText-addons/cuda_lint_perl . Does this change need new Perl ? Perl next-gen?

**Comment by demanuel** [comment]
it works with perl 5.34. 
To be honest i'm not sure if it won't break compability with older perl versions. For modern perl (everything above 5.10) it should be fine, but i would need to make more tests. I will provide more info tomorrow.

**Comment by demanuel** [comment]
@CudaText-addons 

Tested with perl 5.30 and with perl 5.16 (this is the included perl in RHEL 7.9 - lowest version with current status).

Both versions worked as expected.

**Comment by Alexey-T** [comment]
Thanks. applied + updated the linter in addons.
